inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - 'config.ru'
    - '*.gemspec'
    - 'exe/*'
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
  Exclude:
    - 'classes/**/*'
    - 'gemfiles/vendor/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'

# Typical construction is
#   assert_match /something/, test_subject
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'test/**/*.rb'

Layout/AssignmentIndentation:
  IndentationWidth: 4

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
  IndentationWidth: 4

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/LineLength:
  Max: 107
  AllowHeredoc: true
  AllowURI: true
  IgnoreCopDirectives: true
  Exclude:
    - 'config/initializers/secret_token.rb'
    - 'db/schema*.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/routes.rb'
    - 'db/schema*.rb'

Naming/VariableNumber:
  Enabled: false

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Exclude:
    - 'db/migrate/*.rb'

Rails/FilePath:
  Enabled: false

Security/Eval:
  Exclude:
    - gemfiles/*.gemfile # We know of no other way to share common Gemfile partials

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/FormatString:
  EnforcedStyle: percent

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Exclude:
    - 'db/schema*.rb'

Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  ConvertCodeThatCanStartToReturnNil: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
