inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'gemfiles/vendor/**/*'

Rails:
  Enabled: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false

Style/SafeNavigation:
  ConvertCodeThatCanStartToReturnNil: true
